dist: bionic
language: generic
python:
  - 3.6
rvm:
  - 2.6.3
addons:
  apt:
    update: true
    packages:
      - python3-setuptools
      - python3-pip
before_install:
  - java -version
  - python3 --version
  - pip3 --version
install:
  - pip3 install --user bs4
  - gem install jekyll
cache:
  bundler: true
  pip: true
branches:
  only:
  - master
script:
  - export PRIVATE_KEY_FILE=~/.ssh/hurl.dev
  - echo "$PRIVATE_KEY" > "$PRIVATE_KEY_FILE"
  - chmod 600 "$PRIVATE_KEY_FILE"
  - cd sites
  - ./build.sh || travis_terminate 1
  - ./deploy.sh || travis_terminate 1

