name: Check

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  check-style:
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up build env
        run: |
          python3 --version
          pip3 --version
          sudo apt-get install python3-setuptools python3-pip
          pip3 install --user -r ./sites/requirements.txt
      - name: Check style
        run: |
          cd sites
          ./check_fmt.sh
